backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

site_url: https://elated-almeida-6f5495.netlify.com/

collections:
  - label: "Projects"
    name: "projects"
    folder: "src/markdown/projects"
    slug: "{{slug}}"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "project",
        }
      - { label: "Project ID", name: "id", widget: "string", plac }
      - {
          label: "Project Title",
          name: "title",
          widget: "string",
          required: true,
        }
      - {
          label: "Subtitle",
          name: "subtitle",
          widget: "string",
          required: false,
        }
      - {
          label: "Repository Link",
          name: "repository",
          widget: "string",
          required: true,
        }
      - { label: "Demo Link", name: "demo", widget: "string", required: false }

      - {
          label: "Project Image Desktop",
          name: "desktopImage",
          widget: "image",
          required: true,
        }
      - {
          label: "Image Description",
          hint: "required for screen readers",
          name: "imageAltDesktop",
          widget: "string",
          required: true,
        }
      - { label: "Project Image Mobile", name: "mobileImage", widget: "image" }
      - {
          label: "Image Description",
          hint: "required for screen readers",
          name: "imageAltMobile",
          widget: "string",
          required: true,
        }
      - {
          label: "Project Description",
          name: "description",
          widget: "string",
          required: true,
        }
      - { label: "Project Logo", name: "logo", widget: "image", required: true }
      - {
          label: "Image Description",
          hint: "required for screen readers",
          name: "logoAlt",
          widget: "string",
          required: true,
        }
      - {
          label: "Project Hex Code",
          name: "hex",
          widget: "string",
          required: true,
        }
      - {
          label: "Sections",
          name: "sections",
          widget: "list",
          fields:
            [
              {
                label: "Section Title",
                name: "sectionTitle",
                widget: "string",
                required: true,
              },
              {
                label: "Section Images",
                name: "sectionImages",
                widget: "list",
                fields:
                  [
                    {
                      label: "Image",
                      name: "image",
                      widget: "image",
                      required: true,
                    },
                    {
                      label: "Image Label",
                      name: imageLabel,
                      hint: "required for screen readers",
                      required: true,
                    },
                    {
                      label: "ID",
                      name: "id",
                      widget: "string",
                      default: "[section title]000",
                      required: true,
                    },
                  ],
              },
            ],
          required: false,
        }
  - label: "Information Pages"
    name: "infoPages"
    create: true
    folder: "src/markdown/non-project-pages"
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "infoPage",
        }
      - {
          label: "Page Title",
          name: "pageTitle",
          widget: "string",
          required: true,
        }
      - { label: "Page ID", name: "pageId", widget: "string", required: true }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Dev Icons",
          name: "icons",
          widget: "list",
          fields:
            [
              { label: "Icon Name", name: "iconName", widget: "string" },
              { label: "Icon Category", name: "category", widget: "string" },
              { label: "Icon", name: "icon", widget: "string" },
            ],
          required: false,
        }
